version: '3.8'

services:
  iptv-merger:
    build: .
    container_name: iptv-merger
    environment:
      - TZ=${TZ}
      - PLAYLIST_URL=${PLAYLIST_URL}
      - LOCAL_IP=${LOCAL_IP}
      - CUSTOM_STREAMS=${CUSTOM_STREAMS}
      - CACHE_DURATION_MINUTES=${CACHE_DURATION_MINUTES}
      - MAIN_PLAYLIST_TIMEOUT_HOURS=${MAIN_PLAYLIST_TIMEOUT_HOURS}
      - MAX_TIMEOUT=${MAX_TIMEOUT}
      - LOG_PATH=${LOG_PATH}
      - CHANNEL_GROUP_NAME=${CHANNEL_GROUP_NAME}
    ports:
      - "${PORT}:5000"
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
    restart: unless-stopped